# Generated by Django 3.1.5 on 2021-02-10 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_mpucapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgcapture',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mpucapture',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
