# Generated by Django 3.1.2 on 2021-02-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_imgcapture_date'),
        ('UserProfile', '0003_auto_20210210_2243'),
    ]

    operations = [
    ]
