# Generated by Django 3.1.2 on 2021-03-04 02:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_auto_20210211_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('img', models.BinaryField()),
                ('quarternion', models.BinaryField()),
                ('gravity', models.BinaryField()),
                ('ypr', models.BinaryField()),
                ('gyro', models.BinaryField()),
                ('accel', models.BinaryField()),
                ('linaccel', models.BinaryField()),
                ('linaccelinworld', models.BinaryField()),
                ('euler', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='mpucapture',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImgCapture',
        ),
        migrations.DeleteModel(
            name='MpuCapture',
        ),
    ]
