# Generated by Django 3.1.2 on 2021-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_auto_20210303_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacapture',
            name='sessionid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
